<a href="https://colab.research.google.com/github/bohuslavska/Hillel/blob/main/%D0%94%D0%97_1_%D0%91%D0%BE%D0%B3%D1%83%D1%81%D0%BB%D0%B0%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_(Hillel).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
#Matrix multiplication without Numpy

X = [[1, 7, 3],
    [3, 5, 6],
    [6, 8, 9]]

Y = [[1, 1, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

def matrix_dot_matrix(X, Y):
  if len(X[0]) != len(Y):
    print("The number of columns in the first matrix doesn't match the number of rows in the second matrix. Multiplication is impossible.")
    return []
  else:
    output_matrix = []
    for i in range(len(X)):
     output_matrix.append([0] * len(Y[0]))
    for i in range(len(X)):
      for j in range(len(Y[0])):
       for k in range(len(Y)):
         output_matrix[i][j] += X[i][k] * Y[k][j]
  return output_matrix

matrix_dot_matrix(X, Y)

[[55, 65, 49, 5], [57, 68, 72, 12], [90, 107, 111, 21]]

In [30]:
#Matrix multiplication with NumPy

X = [[1, 7, 3],
    [3, 5, 6],
    [6, 8, 9]]

Y = [[1, 1, 1, 2],
   [6, 7, 3, 0],
   [4, 5, 9, 1]]

import numpy as np
print(np.dot(X,Y))

[[ 55  65  49   5]
 [ 57  68  72  12]
 [ 90 107 111  21]]


In [31]:
#Speed comparison

#Matrix multiplication without Numpy

X = []
for i in range(200):
  X.append([12126273] * 200)

Y = []
for i in range(200):
  Y.append([1212627367] * 100)

from datetime import datetime
import time
start_time_1 = datetime.now()

def matrix_dot_matrix(X, Y):
  if len(X[0]) != len(Y):
    print("The number of columns in the first matrix doesn't match the number of rows in the second matrix. Multiplication is impossible.")
    return []
  else:
    output_matrix = []
    for i in range(len(X)):
     output_matrix.append([0] * len(Y[0]))
    for i in range(len(X)):
      for j in range(len(Y[0])):
       for k in range(len(Y)):
         output_matrix[i][j] += X[i][k] * Y[k][j]
  return output_matrix

matrix_dot_matrix(X, Y)

print(datetime.now() - start_time_1)

0:00:01.236100


In [32]:
#Matrix multiplication with NumPy

X = []
for i in range(200):
  X.append([12126273] * 200)

Y = []
for i in range(200):
  Y.append([1212627367] * 100)

from datetime import datetime
import time
start_time_2 = datetime.now()

import numpy as np
np.dot(X,Y)

print(datetime.now() - start_time_2)

0:00:00.009717


Conclusion: **NumPy performs faster.**